Fix udf_samples building issue if machine has a very old boost installed
udf_samples makefile doesn't use ${CLANG_INCLUDE_FLAGS} so it will use
the default boost installation. If dev env has a very old boost installed,
you could get the following comiling error.
  ../udf/udf.h:143:3: error: unknown type name 'uint8_t'
    uint8_t* Allocate(int byte_size);
    ^

Change-Id: I3878b9d73d6022855b0cfbbdbee17eaf4c2557e1
Reviewed-on: http://gerrit.cloudera.org:8080/692
Reviewed-by: Martin Grund <mgrund@cloudera.com>
Tested-by: Internal Jenkins